### ISSUE TITLE
The inconsistent bounding box annotations in the dataset

### ISSUE THREAD

**Issue by SidraHanif180** [GoodNotes/GNHK-dataset#2]
Hi,

Thanks for collecting the handwriting dataset with bounding box annotation.

I recently started using GNHK for my research and found out that there are a couple of inconsistent annotations in the datasets. By inconsistent, I mean that some images are horizontal, but their annotations correspond to their vertical counterpart. Please see a case below:
![eng_AS_041](https://user-images.githubusercontent.com/21314532/152180784-b41c9766-92f8-4926-b716-8618ce10437c.png)
Please let me know if I am missing anything while plotting these annotations. That would be helpful for me.

**Comment by jonomon** [comment]
Hi @SidraHanif180 thanks for the issue.

We found the same issue when reading the image with PIL. 
Please try to read the image with openCV `cv2.imread` and see if it works.

**Comment by SidraHanif180** [comment]
Perfect! Everything actually looks fine.
