### ISSUE TITLE
Dataset download link don't work

### ISSUE THREAD

**Issue by skalinin** [GoodNotes/GNHK-dataset#3]
Hi! Your dataset link is not working. Could you add a new one please?

**Comment by alwc** [comment]
Hi @skalinin, we will be updating the website later this week. Here are the download links:

Google Drive
- [SageMaker (Train & Test)](https://drive.google.com/drive/folders/1KXu55SBzyyZf0Ek-F6Kudre1tWd9dDC2?usp=sharing)
- [Paper (Train & Test)](https://drive.google.com/drive/folders/1YMdE1cP9ZSUxzwycCbrgQjVN_cy2gIw1?usp=sharing)

Baidu Netdisk
- [Paper (Train) [pw: dr6b]](https://pan.baidu.com/s/1HZvfP3CwTvCwAuX1yIhmYg)
- [Paper (Test) [pw: 6h6s]](https://pan.baidu.com/s/1D6BDo0qore9SgP8KBOVKsQ)
